### ISSUE TITLE
Creating new project using NPX and demo content doesn't work

### ISSUE THREAD

**Issue by jj-plane** [Kentico/kontent-starter-corporate-next-js#57] opened 2021-12-08 18:51 UTC
### Brief bug description

When following the 'How To Use' steps in the README file, users will see a server error with the following message: 

> Error: Error serializing `.data.config.item.elements.favicon.value[0].renditions` returned from `getStaticProps` in "/[[...slug]]".
> Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.

### Repro steps

1. Execute `create-next-app` with NPM with the following command: 
`npx create-next-app --example https://github.com/Kentico/kontent-starter-corporate-next-js kontent-starter-corporate-next-js`
2. Copy the .env.template file into .env file
3. Run development server with `npm run dev`
4. See error on http://localhost:3000/

### Expected behavior

You should see the running project at this point. 

### Test environment

 - Platform/OS: Windows 10
 - Browser: all

### Screenshots

![directory](https://user-images.githubusercontent.com/9252685/145266509-2dc402c0-f123-4f53-8d7c-1eb1d6b2f749.PNG)
![error](https://user-images.githubusercontent.com/9252685/145266512-0d6218de-d2e3-468b-9357-0ce58b7a48b9.PNG)

**Comment by Simply007** [comment] 2021-12-09 07:49
Hello @jj-plane,

thanks for the notification. The error is caused by the new feature "renditions" which is transformed into `undefined` instead of a null/empty array. I have pushed a quick fix (https://github.com/Kentico/kontent-starter-corporate-next-js/commit/64aacca4953eea783c9a7ab5263a6049e0f8ff12), so that you are not blocked. You should now be good to go to start with version 11.1.0 of the JS SDK.

But I will keep this issue open and try to find a solution allowing to use the latest version of the JS SDK

**Comment by Simply007** [comment] 2021-12-09 08:32
The issue was fixed in https://github.com/Kentico/kontent-delivery-sdk-js/commit/da7ff461aad6dbf04c31dabdbcd4c9a11cdf743e

Upgrading back to latest SDK version: 01c173c

**Closed by Simply007** 2021-12-09 08:32 UTC
Labels: bug

**Comment by jj-plane** [comment] 2021-12-09 14:11
Just confirmed this works. Thanks for your quick work @Simply007.  Your hard work on these projects is a valuable resource.

**Comment by Simply007** [comment] 2021-12-09 14:13
> Just confirmed this works. Thanks for your quick work @Simply007. Your hard work on these projects is a valuable resource.

Thank you @jj-plane!
