### ISSUE TITLE
hydrateContentItemSingleResponse return duplicate items with underscore in their names

### ISSUE THREAD

**Issue by CAtSG** [Kentico/kontent-starter-corporate-next-js#47] opened 2021-07-30 17:14 UTC
### Expected result

What would cause hydrateContentItemSingleResponse() to return duplicate items with underscore in their names?

### Additional context

Add any other context or guidelines here.

### Resources

* URL
![hydrateContentItemSingleResponse](https://user-images.githubusercontent.com/37556423/127688431-eb221868-f787-4492-8c66-d4320c1e5002.png)
[response_from_hydrateContentItemSingleResponse.txt](https://github.com/Kentico/kontent-starter-corporate-next-js/files/6909086/response_from_hydrateContentItemSingleResponse.txt)
[pass_into_hydrateContentItemSingleResponse.txt](https://github.com/Kentico/kontent-starter-corporate-next-js/files/6909087/pass_into_hydrateContentItemSingleResponse.txt)

**Comment by Simply007** [comment] 2021-08-02 06:14
Hello @CAtSG,

this might be rather a question on [Kontent  Delivery SDK](https://github.com/Kentico/kontent-delivery-sdk-js), because `hydrateContentItemSingleResponse` is using the Delivery SDK's mapping service to map back the response. @Enngage might have some idea why this happens.

It might be able to prevent this behavior with [ custom `elementResolver`](https://github.com/Kentico/kontent-delivery-sdk-js/blob/master/DOCS.md#use-custom-models-for-custom-elements), but this would need a shoot.

Are you able to share some reproducible environment or a project ID I could test it on?

> Just FYI - we are working on a Javascript Modularization on Delivery SDK and as a part of that the models the SDK produces might not be class-based anymore so that this approach of serializing and deserializing the data might not be needed once the new version is out. The refactoring is currently in the early stages, so I am not able to estimate when/whether it is out, but I wanted to give you some more insights.

**Comment by Simply007** [comment] 2021-08-02 06:44
According to the currently solution, I would like to sommarize the current data fetching approach and why it was chosen.

Currently it is not possible to pass Classes as a result of Next.js's `getStaticProps` and `getServerSideProps` methods, but the Delivery Client SDK is returning data in Classes.

So the Classes are transfromed to raw JSONs and passed to Next.js top level component `_app.js` and then transform back to classes (because React itself is capable of using Classes as React Props) - The process in described in [Data loading section in README](https://github.com/Kentico/kontent-starter-corporate-next-js#data-loading)

**Comment by Simply007** [comment] 2021-08-04 07:52
> Hello @CAtSG,
> 
> this might be rather a question on [Kontent Delivery SDK](https://github.com/Kentico/kontent-delivery-sdk-js), because `hydrateContentItemSingleResponse` is using the Delivery SDK's mapping service to map back the response. @Enngage might have some idea why this happens.
> 
> It might be able to prevent this behavior with [ custom `elementResolver`](https://github.com/Kentico/kontent-delivery-sdk-js/blob/master/DOCS.md#use-custom-models-for-custom-elements), but this would need a shoot.
> 
> Are you able to share some reproducible environment or a project ID I could test it on?

@CAtSG - I am not able to reproduce the issue locally. I would need at least the input `response` object which is placed into the `hydrateContentItemSingleResponse` as a first paramater, but ideally the response from `/items/item_codename` so that I can reproduce the issue.

It might be probably a [Default Collision resolver](https://github.com/Kentico/kontent-delivery-sdk-js/blob/3077fde2dfdacb17fe71b2ff5318392849d4df85/lib/config/default-collision-resolver.ts#L3) applied, but that would lead to just one set of elements with underscore I guess.

**Comment by CAtSG** [comment] 2021-08-04 23:05
Hello @Simply007,

Thanks looking into this.  Some updates were made to the content models in Kentico and now the duplicates aren't showing anymore.  I am not sure what caused the issue and what fixed it.

**Comment by Simply007** [comment] 2021-08-09 08:00
OK, thanks for getting back. I will close this issue for now.

If you encounter the issue again, feel free to re-open it  - ideally with the `response` object which is placed into the `hydrateContentItemSingleResponse` as a first parameter, or with the response from `/items/item_codename`.

**Closed by Simply007** 2021-08-09 08:00 UTC
